/**
 * Sample Data for Testing
 * Provides mock data for development and testing
 */

import {
  Deal,
  DealType,
  DealCategory,
  DealComplexity,
  Card,
  CardTier,
  CardNetwork,
  TrackerItem,
  TrackerStatus,
  GoalType,
  UpcomingAction,
} from '@models';

// Sample Deals
export const sampleDeals: Deal[] = [
  {
    id: '1',
    title: 'HDFC Payzapp ₹500 Voucher',
    subtitle: 'Link card to UPI and make 4 transactions',
    type: DealType.HOT,
    category: DealCategory.SPEND,
    value: '~50% Cashback 💰',
    daysLeft: 2,
    requirements: [
      { id: 'r1', description: 'Link card to Payzapp UPI' },
      { id: 'r2', description: 'Min ₹250 per transaction' },
      { id: 'r3', description: 'Valid: Nov 7-30, 2024' },
    ],
    cardId: '1',
    cardName: 'HDFC Regalia',
    bankName: 'HDFC Bank',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: '2',
    title: 'HSBC → Marriott Bonvoy +40%',
    subtitle: 'Transfer points with 40% bonus until Dec 10',
    type: DealType.TRANSFER,
    category: DealCategory.TRANSFER,
    value: 'Limited Time',
    daysLeft: 23,
    cardName: 'HSBC Platinum',
    createdAt: new Date('2024-11-10'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: '3',
    title: 'Amex Gold 90K Points',
    subtitle: 'Elevated offer! Historical high: 90K',
    type: DealType.WELCOME,
    category: DealCategory.WELCOME,
    value: 'Best Offer Available',
    createdAt: new Date('2024-11-12'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: '4',
    title: 'Tata Neu + Big Basket GC',
    subtitle: '12.5% total return via triple stack',
    type: DealType.STACKING,
    category: DealCategory.SPEND,
    complexity: DealComplexity.COMPLEX,
    value: 'High Value',
    createdAt: new Date('2024-11-13'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: '5',
    title: 'ICICI Savings Account',
    subtitle: '₹1000 on ₹25K MAB for 2 months',
    type: DealType.BANK_BONUS,
    category: DealCategory.SPEND,
    complexity: DealComplexity.EASY,
    value: 'Quick Win',
    daysLeft: 30,
    createdAt: new Date('2024-11-14'),
    updatedAt: new Date('2024-11-15'),
  },
];

// Sample Cards
export const sampleCards: Card[] = [
  {
    id: '1',
    name: 'HDFC Regalia',
    displayName: 'HDFC Regalia Credit Card',
    bankName: 'HDFC Bank',
    tier: CardTier.PREMIUM,
    network: CardNetwork.VISA,
    cardType: 'Premium Rewards Card',
    gradientColors: ['#667eea', '#764ba2'],
    annualFee: 2500,
    activeOffersCount: 5,
    feeDaysRemaining: 45,
    isActive: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
  {
    id: '2',
    name: 'Axis Magnus',
    displayName: 'Axis Bank Magnus Credit Card',
    bankName: 'Axis Bank',
    tier: CardTier.PREMIUM,
    network: CardNetwork.VISA,
    cardType: 'Premium Rewards Card',
    gradientColors: ['#F093FB', '#F5576C'],
    annualFee: 10000,
    activeOffersCount: 3,
    feeDaysRemaining: 280,
    isActive: true,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
  {
    id: '3',
    name: 'Amex Gold',
    displayName: 'American Express Gold Card',
    bankName: 'American Express',
    tier: CardTier.GOLD,
    network: CardNetwork.AMEX,
    cardType: 'Rewards Card',
    gradientColors: ['#FFD89B', '#19547B'],
    annualFee: 4500,
    activeOffersCount: 2,
    isActive: true,
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
  {
    id: '4',
    name: 'SBI Cashback',
    displayName: 'SBI Cashback Credit Card',
    bankName: 'State Bank of India',
    tier: CardTier.BASIC,
    network: CardNetwork.VISA,
    cardType: 'Cashback Card',
    gradientColors: ['#4FACFE', '#00F2FE'],
    annualFee: 999,
    activeOffersCount: 3,
    isActive: true,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
  {
    id: '5',
    name: 'ICICI Coral',
    displayName: 'ICICI Bank Coral Credit Card',
    bankName: 'ICICI Bank',
    tier: CardTier.SILVER,
    network: CardNetwork.VISA,
    cardType: 'Lifestyle Card',
    gradientColors: ['#FA709A', '#FEE140'],
    annualFee: 500,
    activeOffersCount: 1,
    feeDaysRemaining: 240,
    isActive: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
];

// Sample Tracker Items
export const sampleTrackerItems: TrackerItem[] = [
  {
    id: 't1',
    title: 'HDFC Payzapp Offer',
    goalType: GoalType.TRANSACTION_COUNT,
    status: TrackerStatus.IN_PROGRESS,
    progress: {
      current: 2,
      target: 4,
      unit: 'transactions',
      percentage: 50,
    },
    daysRemaining: 2,
    dealId: '1',
    cardId: '1',
    startDate: new Date('2024-11-07'),
    endDate: new Date('2024-11-30'),
    createdAt: new Date('2024-11-07'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
  {
    id: 't2',
    title: 'Axis Magnus Welcome Bonus',
    goalType: GoalType.SPENDING,
    status: TrackerStatus.IN_PROGRESS,
    progress: {
      current: 300000,
      target: 400000,
      unit: '₹',
      percentage: 75,
    },
    daysRemaining: 45,
    cardId: '2',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-12-31'),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
  {
    id: 't3',
    title: 'ICICI Coral Cashback',
    goalType: GoalType.MILESTONE,
    status: TrackerStatus.IN_PROGRESS,
    progress: {
      current: 1,
      target: 3,
      unit: 'milestones',
      percentage: 33,
    },
    daysRemaining: 7,
    cardId: '5',
    startDate: new Date('2024-11-01'),
    endDate: new Date('2024-11-24'),
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-15'),
    userId: 'user1',
  },
];

// Sample Upcoming Actions
export const sampleUpcomingActions: UpcomingAction[] = [
  {
    id: 'a1',
    title: 'Chase Sapphire Application',
    description: 'Eligible in 18 days',
    daysUntil: 18,
    actionType: 'application',
    status: 'ready',
    priority: 'medium',
    userId: 'user1',
  },
  {
    id: 'a2',
    title: 'HDFC Regalia Annual Fee',
    description: 'Due in 45 days',
    daysUntil: 45,
    actionType: 'fee_payment',
    status: 'action_needed',
    cardId: '1',
    priority: 'high',
    userId: 'user1',
  },
  {
    id: 'a3',
    title: 'Marriott Points Expiry',
    description: '90 days remaining',
    daysUntil: 90,
    actionType: 'points_transfer',
    status: 'pending',
    priority: 'low',
    userId: 'user1',
  },
];
